// <auto-generated />
namespace BookShopAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class suacode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(suacode));
        
        string IMigrationMetadata.Id
        {
            get { return "202201040436335_sua-code"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
