// <auto-generated />
namespace BookShopAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedatetime2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedatetime2));
        
        string IMigrationMetadata.Id
        {
            get { return "202201030925158_change-datetime2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
